# GitLab CI/CD workflow for our mini-CDN project

stages:
  - build
  - test

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository"

build_job:
  stage: build
  tags: ["maven"]
  image: maven:3.9-jdk-21
  script:
    - mvn clean verify -DskipTests
  cache:
    paths:
      - .m2/repository/
  artifacts:
    when: always
    paths:
      - origin/target/mini-cdn-origin-1.0-SNAPSHOT.jar
      - edge/target/mini-cdn-edge-1.0-SNAPSHOT.jar
      - router/target/mini-cdn-router-1.0-SNAPSHOT.jar
      - cli/target/mini-cdn-cli-1.0-SNAPSHOT.jar
    exclude:
      - '**/*-sources.jar'
      - '**/*-javadoc.jar'
      - '**/original-*.jar'
    expire_in: 1 week

test_job:
  stage: test
  tags: ["maven"]
  image: maven:3.9-jdk-21
  script:
    - echo "Running unit tests..."
    - mvn test -B -Dminicdn.admin.token=secret-token
  cache:
    paths:
      - .m2/repository/
  artifacts:
    when: always
    reports:
      junit:
        - "*/target/surefire-reports/TEST-*.xml"
    paths:
      - "*/target/surefire-reports/"
  retry: 1