/*
 * This file is generated by jOOQ.
 */
package de.htwsaar.minicdn.edge.db;

import de.htwsaar.minicdn.edge.db.tables.Users;
import de.htwsaar.minicdn.edge.db.tables.records.UsersRecord;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;

/**
 * A class modelling foreign key relationships and constraints of tables in the
 * default schema.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes", "this-escape"})
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<UsersRecord> USERS__PK_USERS =
            Internal.createUniqueKey(Users.USERS, DSL.name("pk_users"), new TableField[] {Users.USERS.ID}, true);
}
