/*
 * This file is generated by jOOQ.
 */
package de.htwsaar.minicdn.edge.db;

import de.htwsaar.minicdn.edge.db.tables.Users;

/**
 * Convenience access to all tables in the default schema.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes", "this-escape"})
public class Tables {

    /**
     * The table <code>users</code>.
     */
    public static final Users USERS = Users.USERS;
}
