spring.config.import=optional:file:../.env[.properties]
spring.config.on-not-found=ignore

server.port=8082
cdn.edge-launcher.enabled=true
cdn.edge-launcher.jar-path=../edge/target/edge-1.0-SNAPSHOT-exec.jar

server.error.include-message=always
server.error.include-stacktrace=always

# Region -> Edge Base URL
cdn.edges.eu-west=http://localhost:8081
# cdn.edges.us-east=http://localhost:8083

# Admin Authentication
minicdn.admin.token=${MINICDN_ADMIN_TOKEN}

cdn.origin.base-url=http://localhost:8080
cdn.origin.spares=
cdn.origin.cluster.state-file=data/origin-cluster-state.properties
cdn.origin.health.interval-ms=5000
cdn.origin.health.timeout-ms=1000
cdn.origin.edge-sync.timeout-ms=1500
