/*
 * This file is generated by jOOQ.
 */
package de.htwsaar.minicdn.edge.db.tables;


import de.htwsaar.minicdn.edge.db.DefaultSchema;
import de.htwsaar.minicdn.edge.db.Indexes;
import de.htwsaar.minicdn.edge.db.Keys;
import de.htwsaar.minicdn.edge.db.tables.records.CacheEntriesRecord;

import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class CacheEntries extends TableImpl<CacheEntriesRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>cache_entries</code>
     */
    public static final CacheEntries CACHE_ENTRIES = new CacheEntries();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<CacheEntriesRecord> getRecordType() {
        return CacheEntriesRecord.class;
    }

    /**
     * The column <code>cache_entries.path</code>.
     */
    public final TableField<CacheEntriesRecord, String> PATH = createField(DSL.name("path"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>cache_entries.local_path</code>.
     */
    public final TableField<CacheEntriesRecord, String> LOCAL_PATH = createField(DSL.name("local_path"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>cache_entries.content_type</code>.
     */
    public final TableField<CacheEntriesRecord, String> CONTENT_TYPE = createField(DSL.name("content_type"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>cache_entries.size_bytes</code>.
     */
    public final TableField<CacheEntriesRecord, Integer> SIZE_BYTES = createField(DSL.name("size_bytes"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>cache_entries.sha256</code>.
     */
    public final TableField<CacheEntriesRecord, String> SHA256 = createField(DSL.name("sha256"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>cache_entries.created_ts</code>.
     */
    public final TableField<CacheEntriesRecord, Integer> CREATED_TS = createField(DSL.name("created_ts"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>cache_entries.last_access_ts</code>.
     */
    public final TableField<CacheEntriesRecord, Integer> LAST_ACCESS_TS = createField(DSL.name("last_access_ts"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>cache_entries.expires_ts</code>.
     */
    public final TableField<CacheEntriesRecord, Integer> EXPIRES_TS = createField(DSL.name("expires_ts"), SQLDataType.INTEGER.nullable(false), this, "");

    private CacheEntries(Name alias, Table<CacheEntriesRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private CacheEntries(Name alias, Table<CacheEntriesRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>cache_entries</code> table reference
     */
    public CacheEntries(String alias) {
        this(DSL.name(alias), CACHE_ENTRIES);
    }

    /**
     * Create an aliased <code>cache_entries</code> table reference
     */
    public CacheEntries(Name alias) {
        this(alias, CACHE_ENTRIES);
    }

    /**
     * Create a <code>cache_entries</code> table reference
     */
    public CacheEntries() {
        this(DSL.name("cache_entries"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.IDX_CACHE_EXPIRES, Indexes.IDX_CACHE_LAST_ACCESS);
    }

    @Override
    public UniqueKey<CacheEntriesRecord> getPrimaryKey() {
        return Keys.CACHE_ENTRIES__PK_CACHE_ENTRIES;
    }

    @Override
    public CacheEntries as(String alias) {
        return new CacheEntries(DSL.name(alias), this);
    }

    @Override
    public CacheEntries as(Name alias) {
        return new CacheEntries(alias, this);
    }

    @Override
    public CacheEntries as(Table<?> alias) {
        return new CacheEntries(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public CacheEntries rename(String name) {
        return new CacheEntries(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public CacheEntries rename(Name name) {
        return new CacheEntries(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public CacheEntries rename(Table<?> name) {
        return new CacheEntries(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CacheEntries where(Condition condition) {
        return new CacheEntries(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CacheEntries where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CacheEntries where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CacheEntries where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public CacheEntries where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public CacheEntries where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public CacheEntries where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public CacheEntries where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CacheEntries whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CacheEntries whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
