/*
 * This file is generated by jOOQ.
 */
package de.htwsaar.minicdn.edge.db.tables.records;

import de.htwsaar.minicdn.edge.db.tables.CacheEntries;
import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;

/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes", "this-escape"})
public class CacheEntriesRecord extends UpdatableRecordImpl<CacheEntriesRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>cache_entries.path</code>.
     */
    public void setPath(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>cache_entries.path</code>.
     */
    public String getPath() {
        return (String) get(0);
    }

    /**
     * Setter for <code>cache_entries.local_path</code>.
     */
    public void setLocalPath(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>cache_entries.local_path</code>.
     */
    public String getLocalPath() {
        return (String) get(1);
    }

    /**
     * Setter for <code>cache_entries.content_type</code>.
     */
    public void setContentType(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>cache_entries.content_type</code>.
     */
    public String getContentType() {
        return (String) get(2);
    }

    /**
     * Setter for <code>cache_entries.size_bytes</code>.
     */
    public void setSizeBytes(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>cache_entries.size_bytes</code>.
     */
    public Integer getSizeBytes() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>cache_entries.sha256</code>.
     */
    public void setSha256(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>cache_entries.sha256</code>.
     */
    public String getSha256() {
        return (String) get(4);
    }

    /**
     * Setter for <code>cache_entries.created_ts</code>.
     */
    public void setCreatedTs(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>cache_entries.created_ts</code>.
     */
    public Integer getCreatedTs() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>cache_entries.last_access_ts</code>.
     */
    public void setLastAccessTs(Integer value) {
        set(6, value);
    }

    /**
     * Getter for <code>cache_entries.last_access_ts</code>.
     */
    public Integer getLastAccessTs() {
        return (Integer) get(6);
    }

    /**
     * Setter for <code>cache_entries.expires_ts</code>.
     */
    public void setExpiresTs(Integer value) {
        set(7, value);
    }

    /**
     * Getter for <code>cache_entries.expires_ts</code>.
     */
    public Integer getExpiresTs() {
        return (Integer) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CacheEntriesRecord
     */
    public CacheEntriesRecord() {
        super(CacheEntries.CACHE_ENTRIES);
    }

    /**
     * Create a detached, initialised CacheEntriesRecord
     */
    public CacheEntriesRecord(
            String path,
            String localPath,
            String contentType,
            Integer sizeBytes,
            String sha256,
            Integer createdTs,
            Integer lastAccessTs,
            Integer expiresTs) {
        super(CacheEntries.CACHE_ENTRIES);

        setPath(path);
        setLocalPath(localPath);
        setContentType(contentType);
        setSizeBytes(sizeBytes);
        setSha256(sha256);
        setCreatedTs(createdTs);
        setLastAccessTs(lastAccessTs);
        setExpiresTs(expiresTs);
        resetTouchedOnNotNull();
    }
}
