/*
 * This file is generated by jOOQ.
 */
package de.htwsaar.minicdn.edge.db;

import de.htwsaar.minicdn.edge.db.tables.CacheEntries;

/**
 * Convenience access to all tables in the default schema.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes", "this-escape"})
public class Tables {

    /**
     * The table <code>cache_entries</code>.
     */
    public static final CacheEntries CACHE_ENTRIES = CacheEntries.CACHE_ENTRIES;
}
